version: "3.7"
services:
  nginx:
    image: nginx
    ports: 
      - "8062:80"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf" 
      - "./app:/var/www" 
    depends_on:
      - php-fpm
    networks: 
      - app_net
    container_name:
      sin-nginx
  php-fpm:
    image: php:fpm
    ports:
      - "9002:9000"
    volumes:
      - "./app:/var/www/html" 
    networks:
      - app_net
    container_name:
      sin-php
  mysql:
    image: mysql
    ports: 
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks: 
      - app_net
    container_name: 
      sin-mysql
  workspace:
    image: alpine
    volumes:
      - "./app:/var/www" 
    ports: 
      - "4444:22"
    networks:
      - app_net
    container_name: sin-workspace
networks:
  app_net:
    driver: bridge

  

